language: perl
before_install:
 - sudo apt-get update
 - apt-get search libdbus
 - sudo apt-get install libdbus-1
 - sudo apt-get install libsdl1.2-dev

install: cpanm -v --installdeps --notest .

perl:
  - "5.18"
  - "5.16"
  - "5.14"
